// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3381.RobotCode1.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3381.RobotCode1.Robot;

/**
 *
 */
public class CommandLightLED extends Command {
	
	Double flashRate;
	Double redValue;
	Double blueValue;
	Double yellowValue;
	Boolean redFullOn;
	Boolean blueFullOn;
	Boolean yellowFullOn;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public CommandLightLED() {
        setRunWhenDisabled(true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lED);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	flashRate = 0.01;
    	redValue = 0.0;
    	blueValue = 0.5;
    	yellowValue = 1.0;
    	redFullOn = false;
    	blueFullOn = false;
    	yellowFullOn = false;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	
//    	if(redValue <= 1.0 && redFullOn == false) {
//    		redValue = redValue + 0.01;
//    		Robot.lED.setRed(redValue);
//    		Robot.lED.setBlue(redValue);
//    		Robot.lED.setYellow(redValue);
//    	}
//    	else if(redValue <= 0.0 && redFullOn == true) {
//    		redFullOn = false;
//    	}
//    	else {
//    		redFullOn = true;
//    		redValue = redValue - 0.01;
//    		Robot.lED.setRed(redValue);
//    		Robot.lED.setBlue(redValue);
//    		Robot.lED.setYellow(redValue);
//    	}

    	
//    	if(redValue <= 1.0 && redFullOn == false) {
//    		redValue = redValue + flashRate;
//    		Robot.lED.setRed(redValue);
//    	}
//    	else if(redValue <= 0.0 && redFullOn == true) {
//    		redFullOn = false;
//    	}
//    	else {
//    		redFullOn = true;
//    		redValue = redValue - flashRate;
//    		Robot.lED.setRed(redValue);
//    	}
//    	
//    	if(blueValue <= 1.0 && blueFullOn == false) {
//    		blueValue = blueValue + flashRate;
//    		Robot.lED.setBlue(blueValue);
//    	}
//    	else if(blueValue <= 0.0 && blueFullOn == true) {
//    		blueFullOn = false;
//    	}
//    	else {
//    		blueFullOn = true;
//    		blueValue = blueValue - flashRate;
//    		Robot.lED.setBlue(blueValue);
//    	}
//    	
//    	if(yellowValue <= 1.0 && yellowFullOn == false) {
//    		yellowValue = yellowValue + flashRate;
//    		Robot.lED.setYellow(yellowValue);
//    	}
//    	else if(yellowValue <= 0.0 && yellowFullOn == true) {
//    		yellowFullOn = false;
//    	}
//    	else {
//    		yellowFullOn = true;
//    		yellowValue = yellowValue - flashRate;
//    		Robot.lED.setYellow(yellowValue);
//    	}
//    	
//    	flashRate = (Robot.oi.joystick2.getZ() + 1.01) / 2;
    	
//    	Robot.lED.setRed((Robot.oi.joystick2.getZ() + 1) / 2);
//    	Robot.lED.setBlue((Robot.oi.joystick2.getZ() + 1) / 2);
//    	Robot.lED.setYellow((Robot.oi.joystick2.getZ() + 1) / 2);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return Robot.oi.joystick2.getRawButton(1);
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
//    	Robot.lED.setRed(0.0);
//    	Robot.lED.setBlue(0.0);
//    	Robot.lED.setYellow(0.0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
